/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.visao;

import br.com.controle.Calculos;
import javax.swing.JOptionPane;

/**
 *
 * @author contabilidade
 */
public class Tela extends javax.swing.JFrame {
    Calculos c = new Calculos();
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTvalor1 = new javax.swing.JTextField();
        jTvalor2 = new javax.swing.JTextField();
        jLresultado = new javax.swing.JLabel();
        jRsomar = new javax.swing.JRadioButton();
        jRsubtracao = new javax.swing.JRadioButton();
        jRmultiplicar = new javax.swing.JRadioButton();
        jRdivisao = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Digite o 1° valor:");

        jLabel2.setText("Digite o 2° valor:");

        jTvalor1.setColumns(5);
        jTvalor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTvalor1ActionPerformed(evt);
            }
        });

        jTvalor2.setColumns(5);

        jLresultado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLresultado.setForeground(new java.awt.Color(204, 102, 0));
        jLresultado.setText("0.00");

        buttonGroup1.add(jRsomar);
        jRsomar.setText("+");
        jRsomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRsomarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRsubtracao);
        jRsubtracao.setText("-");
        jRsubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRsubtracaoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRmultiplicar);
        jRmultiplicar.setText("*");
        jRmultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRmultiplicarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRdivisao);
        jRdivisao.setText("/");
        jRdivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdivisaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTvalor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTvalor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLresultado))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRsomar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRsubtracao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRmultiplicar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRdivisao)))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTvalor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTvalor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRsomar)
                    .addComponent(jRsubtracao)
                    .addComponent(jRmultiplicar)
                    .addComponent(jRdivisao))
                .addGap(10, 10, 10)
                .addComponent(jLresultado)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTvalor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTvalor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTvalor1ActionPerformed

    private void jRsomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRsomarActionPerformed
        // TODO add your handling code here:
        if(jTvalor1.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "");
            jTvalor1.requestFocus();
        }
        else if(jTvalor2.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "");
            jTvalor2.requestFocus();
        }
        else{
       c.setValor1(Double.valueOf(jTvalor1.getText()));
       c.setValor2(Double.valueOf(jTvalor2.getText()));
       jLresultado.setText(""+c.somar());
        }
    }//GEN-LAST:event_jRsomarActionPerformed

    private void jRsubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRsubtracaoActionPerformed
        // TODO add your handling code here:
        if(jTvalor1.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "");
            jTvalor1.requestFocus();
        }
        else if(jTvalor2.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "");
            jTvalor2.requestFocus();
        }
        else{
       c.setValor1(Double.valueOf(jTvalor1.getText()));
       c.setValor2(Double.valueOf(jTvalor2.getText()));
       jLresultado.setText(""+c.somar());
        }
       c.setValor1(Double.valueOf(jTvalor1.getText()));
       c.setValor2(Double.valueOf(jTvalor2.getText()));
       jLresultado.setText(""+c.subtrair());
    }//GEN-LAST:event_jRsubtracaoActionPerformed

    private void jRmultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRmultiplicarActionPerformed
        // TODO add your handling code here:
         c.setValor1(Double.valueOf(jTvalor1.getText()));
       c.setValor2(Double.valueOf(jTvalor2.getText()));
       jLresultado.setText(""+c.multiplicar());
    }//GEN-LAST:event_jRmultiplicarActionPerformed

    private void jRdivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdivisaoActionPerformed
        // TODO add your handling code here:
        if(jTvalor1.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "");
            jTvalor1.requestFocus();
        }
        else if(jTvalor2.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "");
            jTvalor2.requestFocus();
        }
        else{
       c.setValor1(Double.valueOf(jTvalor1.getText()));
       c.setValor2(Double.valueOf(jTvalor2.getText()));
       jLresultado.setText(""+c.somar());
        }
         c.setValor1(Double.valueOf(jTvalor1.getText()));
       c.setValor2(Double.valueOf(jTvalor2.getText()));
       jLresultado.setText(""+c.dividir());
    }//GEN-LAST:event_jRdivisaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLresultado;
    private javax.swing.JRadioButton jRdivisao;
    private javax.swing.JRadioButton jRmultiplicar;
    private javax.swing.JRadioButton jRsomar;
    private javax.swing.JRadioButton jRsubtracao;
    private javax.swing.JTextField jTvalor1;
    private javax.swing.JTextField jTvalor2;
    // End of variables declaration//GEN-END:variables
}
